services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        environment:
            APP_ENV: production
            APP_KEY: base64:Pmvvwd9ghUkQDJawLFYudMCv4wXwYP+gWEITM1PwQv8=
            APP_DEBUG: "true"
            APP_URL: http://localhost:8080
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel_db
            DB_USERNAME: root
            DB_PASSWORD: root
            CACHE_DRIVER: file
        depends_on:
            db:
                condition: service_healthy
        command: >
            php artisan config:clear &&
            php artisan cache:clear &&
            php artisan route:clear &&
            php artisan view:clear &&
            php artisan config:cache &&
            php artisan migrate --force &&
            php artisan serve --host=0.0.0.0 --port=8080

    db:
        image: mariadb:11
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        volumes:
            - ./apache.conf:/etc/apache2/conf-enabled/servername.conf

volumes:
    db_data:
