version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        environment:
            # Ganti dengan env kamu
            APP_ENV: local
            APP_KEY: base64:SomeGeneratedKey
            APP_DEBUG: "true"
            APP_URL: http://localhost:8080
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel_db
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - db
        command: >
            sh -c "
            php artisan config:clear &&
            php artisan cache:clear &&
            php artisan route:clear &&
            php artisan view:clear &&
            php artisan config:cache &&
            php artisan serve --host=0.0.0.0 --port=8080
            "

    db:
        image: mysql:8
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
