version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        environment:
            APP_ENV: production
            APP_KEY: base64:Pmvvwd9ghUkQDJawLFYudMCv4wXwYP+gWEITM1PwQv8=
            APP_DEBUG: "true"
            APP_URL: http://localhost:8080
            DB_CONNECTION: mysql
            DB_HOST: centerbeam.proxy.rlwy.net
            DB_PORT: 36212
            DB_DATABASE: railway
            DB_USERNAME: root
            DB_PASSWORD: QMeGDQekZFdrPkupmQUXQymjEmwaOGRV
        command: >
            sh -c "
            php artisan config:clear &&
            php artisan cache:clear &&
            php artisan route:clear &&
            php artisan view:clear &&
            php artisan config:cache &&
            php artisan serve --host=0.0.0.0 --port=8080
            "
